export const routesConfig = {
  mainPage: { name: 'Main', path: '/' },
  auctionsPage: { name: 'Auction', path: '/auctions' },
  myAuctionsPage: { name: 'My auctions', path: '/myauctions' },
  newsPage: { name: 'News', path: '/news' },
  Messages: { name: 'Messages', path: '/messages' },
  partnerPage: { name: 'Partner program', path: '/partnerProgram' },
  tokensPage: { name: 'Tokens', path: '/tokens' },
  winnersListPage: { name: 'Winner list', path: '/winnerList' },
  lotPage: { name: 'Lot/:id', path: '/:id' },
  cabinetPage: { name: 'Cabinet', path: '/cabinet' },
  notificationsPage: { name: 'Notifications', path: '/notifications' },
  questionsPage: { name: 'Questions', path: '/questions' },
  supportPage: { name: 'SupportPage', path: '/support' },
  signIn: { name: 'SignIn', path: '/SignIn' },
  signUp: { name: 'SignUp', path: '/SignUp' },
  resetPassword: { name: 'ResetPassword', path: '/ResetPassword' },
  newPassword: { name: 'NewPassword', path: '/NewPassword' },
}
